server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      timeout: 30m
  port: 80

# JSP, mustache 원하는거 사용
spring:
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB      
  datasource:
    url: jdbc:mysql://13.211.47.78:3306/placeStation?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sa1953vb!
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        provider:  #프로 바이더는 고정값
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        registration:
          kakao:
            client-id: aeff9f33b9d74346008005686767c513
            client-secret: mxDjnVGxkafToFR9bvyNtMJknK5Etnxw # 시크릿 키
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
          naver:
            client-id: OoIwslayQE_qOrByEI0U
            client-secret: Ij6j_GrSZd # 시크릿 키
            redirect-uri: localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-authentication-method: POST
            client-name: naver


#  datasource:    
#    url: jdbc:h2:mem:testdb;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: user # 유저 이름
#    password: # 비밀번호 (비워두면 비밀번호 X)
#  h2:
#    console:
#      enabled: true
#  sql:
#    init:
#      data-locations:
#        - classpath:db/table.sql
#        - classpath:db/data.sql



#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true


mybatis:
  mapper-locations:
  - classpath:mapper/**.xml 
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
   
logging:
  level:
    org:
    mybatis: DEBUG
    hibernate: info
    springframework:
        security: DEBUG
        security.oauth2: DEBUG
    

